name: Cancel stale Pages deployment

on:
  workflow_dispatch:

permissions:
  pages: write

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel stale Pages deployment
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh api --method POST
          "repos/${GITHUB_REPOSITORY}/pages/deployments/c557e33104a92570c6a320e65bbc7101c8a44832/cancel"
